### PR TITLE
Update training files and labeling 

### PR DESCRIPTION
**Pull request by MRD2F**
Remove original files no quantized and change the name of the quantized to be the new default training files

### CODE REVIEW

**Comment by mbluj** [comment]
Hello,
I think that files can be labeled as `quantized` as it is information for developers, so I just propose to remove non-quantized ones. Do you agree? I can deal with it myself.
On the contrary, I propose to not keep special Q[uantized] instances of DeepTau and DPFTau producers in configuration to not confuse final users. The quantized producers are code-wise identical as not-quantized ones, so it will be simple to add them for testing purposes if needed.

**Comment by kandrosov** [comment]
Ok. Then, please, wait before merging https://github.com/cms-tau-pog/cmssw/pull/106, because the regex for the version identification should be adjusted to account for a possible `quantized` suffix.

**Comment by mbluj** [comment]
In principle you can swap `quantized` and version number in file names, e.g. `DPFIsolation_2017v0_quantized.pb` => `DPFIsolation_quantized_2017v0.pb` and keep current regex. Regardless of final solution, I propose to comment somewhere (in the python configuration tool?) about the expected format of name of training file to avoid problems. 
Generally, I like your choice that a version is deducted from a file name in the configuration tool rather than in C++ code which is more flexible as allows by-hand adaptations for tests w/o need of recompilation.

**Comment by kandrosov** [comment]
> In principle you can swap `quantized` and version number in file names, e.g. `DPFIsolation_2017v0_quantized.pb` => `DPFIsolation_quantized_2017v0.pb` and keep current regex. 

I propose to loosen constraint on the file name, i.e. require that somewhere in the file name it is specified `{year}v{version}`, e.g. `2017v0`. @MRD2F already applied this in the other PR. She also fixed this PR. So, if you agree and don't have further comments, I think both PRs can be merged.

**Comment by mbluj** [comment]
> > In principle you can swap `quantized` and version number in file names, e.g. `DPFIsolation_2017v0_quantized.pb` => `DPFIsolation_quantized_2017v0.pb` and keep current regex.
> 
> I propose to loosen constraint on the file name, i.e. only require that somewhere in the file name it is specified `{year}v{version}`, e.g. `2017v0`. @MRD2F already applied this in the other PR. She also fixed this PR. So, if you agree and don't have further comments, I think both PRs can be merged.

Sounds good, thank you!

**Pull request merged**
