### PR TITLE
Added final DeepTauID v2p5 model

### PR DESCRIPTION
**Pull request by shedprog**
**PR description:**

In this PR final DeepTauID_v2p5 model is added.
The corresponding path to the non-converted (in tf-format) model can be found under the following public eos location: `/eos/cms/store/group/phys_tau/TauML/prod_2018_v2/mlruns/4/e1f3ddb3c4c94128a34a7635c56322eb` (model hash:`e1f3ddb3c4c94128a34a7635c56322eb`)

The performance study on RUN2 and RUN3 samples can be found under the following link: https://indico.cern.ch/event/1164900/contributions/4891675/attachments/2450061/4204746/FinalModel.pdf 
and study of the base models performance (used as a starting point) https://indico.cern.ch/event/1164900/contributions/4891675/attachments/2450061/4205013/deeptauv2p5_run2_run3_sample_comparison.pdf

**Checks:**

The disagreement between non-splited tf model and split *.pb model is checked.

**P.S:** Thanks, @kandrosov @lucasrussell01 @ofivite @lguzzi for the contribution!

### CODE REVIEW

**Comment by mbluj** [comment]
Hello, I consider these files final v2p5 - is it correct?
What I see in attached slides the updated model files give only small improvement wrt preliminary ones and mostly for anti-mu discriminant. Is this considered as worth merging to official CMSSW?

**Comment by shedprog** [comment]
> Hello, I consider these files final v2p5 - is it correct? What I see in attached slides the updated model files give only small improvement wrt preliminary ones and mostly for anti-mu discriminant. Is this considered as worth merging to official CMSSW?

Hello Michal, in this training adversarial training to mitigate Data/MC disagreement was used, and with adv. NN, you can see that there is no sacrifice in performance, in comparison with the default one.

**Comment by kandrosov** [comment]
Yes, while the performance between the old v2p5 and the new v2p5 is roughly comparable, the main improvement is data-mc agreement at high VSjet bins (e.g. [here](https://indico.cern.ch/event/1164900/contributions/4891675/attachments/2450061/4198838/TauML_adversarial_2405.pdf#page=4)). This disagreement is present also for DeepTau v2p1 and MVA iso. For the final confirmation of how good the data-mc agreement is for the new v2p5, we would need to repeat the complete SF measurement procedure with TauFW, but the results look promising so far. And if it will be confirmed, we plan to implement the same techniques to improve agreement for VSe and VSmu as well.

I think these new NN weights are worth merging into the official CMSSW.

**Comment by mbluj** [comment]
@kandrosov thank you for clarifications. I will go with merging. However, in meantime old DNN-tauIDs were removed for master but not necessarily for 12_4_X (both code and models) so I think I should backport it also for consistency.

**Pull request merged**
